# Generated by Django 3.2.14 on 2022-09-04 21:25

import app_fac.models.user_manager
import datetime
from django.conf import settings
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import stdimage.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyUserAdmin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='email address')),
                ('dt_expiracao', models.DateTimeField(default=datetime.date(1900, 1, 1), verbose_name='Data de Expiracao')),
                ('is_staff', models.BooleanField(default=True, verbose_name='Membro da equipe')),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', app_fac.models.user_manager.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('celular', models.CharField(max_length=20)),
                ('ra', models.IntegerField()),
                ('imagem', stdimage.models.StdImageField(force_min_size=False, upload_to=app_fac.models.user_manager.get_file_path, variations={'thumbnail': {'crop': True, 'height': 480, 'width': 480}}, verbose_name='Imagem')),
                ('dt_expiracao', models.DateField(default=datetime.date(1900, 1, 1), verbose_name='Data de Expiração')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='aluno_usuario', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Aluno',
                'verbose_name_plural': 'Alunos',
                'permissions': [('aluno_access', 'aluno_change')],
            },
        ),
        migrations.CreateModel(
            name='Atividade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255, unique=True)),
                ('descricao', models.TextField(max_length=255)),
                ('conteudo', models.TextField(max_length=255)),
                ('tipo', models.TextField(max_length=255)),
                ('extras', models.TextField(max_length=255)),
            ],
            options={
                'verbose_name': 'Atividade',
                'verbose_name_plural': 'Atividades',
            },
        ),
        migrations.CreateModel(
            name='AtividadeVinculada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('ABERTA', 'Aberta'), ('FECHADA', 'Fechada'), ('PRORROGADA', 'Prorrogada')], max_length=15)),
                ('atividade_vinculada', models.CharField(choices=[('AC1', 'AC1'), ('AC2', 'AC2'), ('AC3', 'AC3'), ('AC4', 'AC4'), ('AC5', 'AC5'), ('AC6', 'AC6'), ('AC7', 'AC7'), ('AC8', 'AC8'), ('AC9', 'AC9'), ('AC10', 'AC10')], default='AC1', max_length=4, verbose_name='Atividade Complementar')),
                ('rotulo', models.CharField(max_length=255)),
                ('dt_inicio', models.DateField(default=datetime.date(1900, 1, 1), verbose_name='Data Inicio')),
                ('dt_fim', models.DateField(default=datetime.date(1900, 1, 1), verbose_name='Data Fim')),
                ('atividade', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app_fac.atividade')),
            ],
            options={
                'verbose_name_plural': 'Atividades Vinculadas',
            },
        ),
        migrations.CreateModel(
            name='Coordenador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('celular', models.CharField(max_length=20)),
                ('rc', models.IntegerField(default=0)),
                ('imagem', stdimage.models.StdImageField(force_min_size=False, upload_to=app_fac.models.user_manager.get_file_path, variations={'thumbnail': {'crop': True, 'height': 480, 'width': 480}}, verbose_name='Imagem')),
                ('data_expiracao', models.DateField(default=datetime.date(1900, 1, 1), verbose_name='Data de Expiracao')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='coordenador_usuario', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Coordenador',
                'verbose_name_plural': 'Coordenadores',
            },
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('descricao', models.TextField(default=None, max_length=2000)),
                ('destaque', models.CharField(default=None, max_length=255)),
                ('mercado_trabalho', models.TextField(max_length=1000)),
                ('periodo', models.CharField(choices=[('MATUTINO', 'MATUTINO'), ('NOTURNO', 'NOTURNO')], default='MATUTINO', max_length=10)),
                ('duracao', models.CharField(blank=True, max_length=255)),
                ('modalidade', models.CharField(choices=[('PRESENCIAL', 'PRESENCIAL'), ('ONLINE', 'ONLINE')], default='PRESENCIAL', max_length=12)),
                ('imagem', stdimage.models.StdImageField(force_min_size=False, upload_to=app_fac.models.user_manager.get_file_path, variations={'thumbnail': {'crop': True, 'height': 500, 'width': 1500}}, verbose_name='Imagem')),
                ('imagem2', stdimage.models.StdImageField(force_min_size=False, upload_to=app_fac.models.user_manager.get_file_path, variations={'thumbnail': {'crop': True, 'height': 480, 'width': 480}}, verbose_name='Imagem dois')),
                ('imagem3', stdimage.models.StdImageField(blank=True, force_min_size=False, upload_to=app_fac.models.user_manager.get_file_path, variations={'thumbnail': {'crop': True, 'height': 330, 'width': 1100}}, verbose_name='Imagem tres')),
                ('coordenador', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='app_fac.coordenador')),
            ],
            options={
                'verbose_name': 'Curso',
                'verbose_name_plural': 'Cursos',
            },
        ),
        migrations.CreateModel(
            name='Disciplina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, unique=True)),
                ('data', models.DateField()),
                ('status', models.CharField(choices=[('AB', 'Aberto'), ('FC', 'Fechado')], default='AB', max_length=2)),
                ('plano_ensino', models.TextField(max_length=5000)),
                ('carga_horaria', models.IntegerField()),
                ('competencias', models.TextField(max_length=1000)),
                ('habilidades', models.TextField(max_length=1000)),
                ('ementa', models.TextField(max_length=5000)),
                ('Conteudo_programatico', models.TextField(max_length=5000)),
                ('bibliografia_basica', models.TextField(max_length=1000)),
                ('bibliografia_complementar', models.TextField(max_length=1000)),
                ('percentual_pratico', models.DecimalField(decimal_places=2, max_digits=13)),
                ('percentual_teorico', models.DecimalField(decimal_places=2, max_digits=13)),
                ('coordenador', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='app_fac.coordenador')),
            ],
            options={
                'verbose_name': 'Disciplina',
                'verbose_name_plural': 'Disciplinas',
            },
        ),
        migrations.CreateModel(
            name='Turma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('turma', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=4)),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app_fac.curso')),
            ],
            options={
                'verbose_name': 'Turma',
                'verbose_name_plural': 'Turmas',
            },
        ),
        migrations.CreateModel(
            name='SolicitacaoMatricula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dt_solicitacao', models.DateField()),
                ('status', models.CharField(choices=[('SO', 'Solicitada'), ('RE', 'Rejeitada'), ('AP', 'Aprovada'), ('CA', 'Cancelada')], default='SO', max_length=4)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app_fac.aluno')),
                ('coordenador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app_fac.coordenador')),
                ('curso', models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='app_fac.curso')),
            ],
            options={
                'verbose_name_plural': 'Solicitação de Matricula',
            },
        ),
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('celular', models.CharField(max_length=20)),
                ('rp', models.IntegerField()),
                ('imagem', stdimage.models.StdImageField(force_min_size=False, upload_to=app_fac.models.user_manager.get_file_path, variations={'thumbnail': {'crop': True, 'height': 480, 'width': 480}}, verbose_name='Imagem')),
                ('data_expiracao', models.DateField(default=datetime.date(1900, 1, 1), verbose_name='Data de Expiracao')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='usuario_professor', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Professor',
                'verbose_name_plural': 'Professores',
            },
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='', verbose_name='foto')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagem', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'imagem',
                'verbose_name_plural': 'imagens',
                'ordering': ('pk',),
            },
        ),
        migrations.CreateModel(
            name='Mensagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assunto', models.TextField(max_length=255)),
                ('referencia', models.TextField(max_length=255)),
                ('conteudo', models.TextField(max_length=255)),
                ('status', models.CharField(choices=[('EN', 'Enviado'), ('LI', 'Lido'), ('RE', 'Respondido')], max_length=3)),
                ('dt_envio', models.DateField()),
                ('dt_resposta', models.DateField()),
                ('resposta', models.TextField(max_length=1000)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app_fac.aluno')),
                ('professor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app_fac.professor')),
            ],
            options={
                'verbose_name_plural': 'Mensagens',
            },
        ),
        migrations.CreateModel(
            name='Matricula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dt_inicio', models.DateField()),
                ('dt_fim', models.DateField()),
                ('status', models.CharField(choices=[('AV', 'Ativa'), ('CA', 'Cancelada'), ('TA', 'Trancada'), ('AE', 'Analise')], default='AE', max_length=4)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app_fac.aluno')),
                ('curso', models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='app_fac.curso')),
                ('solicitacao_matricula', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app_fac.solicitacaomatricula')),
                ('turma', models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='app_fac.turma')),
            ],
            options={
                'verbose_name': 'Matricula',
                'verbose_name_plural': 'Matriculas',
            },
        ),
        migrations.CreateModel(
            name='EntregaAtividade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('resposta', models.TextField(max_length=255)),
                ('dt_entrega', models.DateField()),
                ('status', models.CharField(choices=[('EN', 'Entregue'), ('CO', 'Corrigido')], default='EN', max_length=2)),
                ('nota', models.DecimalField(decimal_places=2, max_digits=5)),
                ('dt_avaliacao', models.DateField()),
                ('obs', models.TextField(max_length=255)),
                ('file', models.FileField(blank=True, null=True, upload_to='file')),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app_fac.aluno')),
                ('atividade_vinculada', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app_fac.atividadevinculada')),
                ('professor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app_fac.professor')),
            ],
            options={
                'verbose_name_plural': 'Entrega das Atividades',
            },
        ),
        migrations.CreateModel(
            name='DisciplinaOfertada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dt_inicio', models.DateField()),
                ('dt_fim', models.DateField()),
                ('ano', models.IntegerField()),
                ('semestre', models.IntegerField()),
                ('metodologia', models.TextField(max_length=255)),
                ('recursos', models.TextField(max_length=255)),
                ('criterio_avaliacao', models.TextField(max_length=1000)),
                ('plano_aula', models.TextField(max_length=1000)),
                ('coordenador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app_fac.coordenador')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app_fac.curso')),
                ('disciplina', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app_fac.disciplina')),
                ('professor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app_fac.professor')),
                ('turma', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app_fac.turma')),
            ],
            options={
                'verbose_name_plural': 'Disciplinas Ofertadas',
                'unique_together': {('curso', 'disciplina', 'turma', 'ano', 'semestre')},
            },
        ),
        migrations.AddField(
            model_name='atividadevinculada',
            name='disciplina_ofertada',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app_fac.disciplinaofertada'),
        ),
        migrations.AddField(
            model_name='atividadevinculada',
            name='professor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app_fac.professor'),
        ),
        migrations.AddField(
            model_name='atividade',
            name='professor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app_fac.professor'),
        ),
    ]
