# Generated by Django 3.2.14 on 2022-09-05 23:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='turma',
            name='curso',
        ),
        migrations.AddField(
            model_name='curso',
            name='disciplina_ofertada',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='app.disciplinaofertada'),
        ),
        migrations.AlterUniqueTogether(
            name='disciplinaofertada',
            unique_together={('disciplina', 'turma', 'ano', 'semestre')},
        ),
        migrations.RemoveField(
            model_name='disciplinaofertada',
            name='curso',
        ),
    ]
