# Generated by Django 3.2.14 on 2022-07-27 01:09

import app_fac.models.user_manager
import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('app_fac', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('celular', models.CharField(max_length=20)),
                ('rp', models.IntegerField()),
                ('imagem', stdimage.models.StdImageField(force_min_size=False, upload_to=app_fac.models.user_manager.get_file_path, variations={'thumbnail': {'crop': True, 'height': 480, 'width': 480}}, verbose_name='Imagem')),
                ('data_expiracao', models.DateField(default=datetime.date(1900, 1, 1), verbose_name='Data de Expiracao')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='usuario_professor', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Professor',
                'verbose_name_plural': 'Professores',
            },
        ),
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('celular', models.CharField(max_length=20)),
                ('ra', models.IntegerField()),
                ('imagem', stdimage.models.StdImageField(force_min_size=False, upload_to=app_fac.models.user_manager.get_file_path, variations={'thumbnail': {'crop': True, 'height': 480, 'width': 480}}, verbose_name='Imagem')),
                ('dt_expiracao', models.DateField(default=datetime.date(1900, 1, 1), verbose_name='Data de Expiração')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='aluno_usuario', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Aluno',
                'verbose_name_plural': 'Alunos',
                'permissions': [('aluno_access', 'aluno_change')],
            },
        ),
    ]
