# Generated by Django 3.2.14 on 2022-07-30 15:34

import app_fac.models.user_manager
import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('app_fac', '0002_aluno_professor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Atividade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255, unique=True)),
                ('descricao', models.TextField(max_length=255)),
                ('conteudo', models.TextField(max_length=255)),
                ('tipo', models.TextField(max_length=255)),
                ('extras', models.TextField(max_length=255)),
                ('professor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app_fac.professor')),
            ],
            options={
                'verbose_name': 'Atividade',
                'verbose_name_plural': 'Atividades',
            },
        ),
        migrations.CreateModel(
            name='AtividadeVinculada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('ABERTA', 'Aberta'), ('FECHADA', 'Fechada'), ('PRORROGADA', 'Prorrogada')], max_length=15)),
                ('atividade_vinculada', models.CharField(choices=[('AC1', 'AC1'), ('AC2', 'AC2'), ('AC3', 'AC3'), ('AC4', 'AC4'), ('AC5', 'AC5'), ('AC6', 'AC6'), ('AC7', 'AC7'), ('AC8', 'AC8'), ('AC9', 'AC9'), ('AC10', 'AC10')], default='AC1', max_length=4, verbose_name='Atividade Complementar')),
                ('rotulo', models.CharField(max_length=255)),
                ('dt_inicio', models.DateField(default=datetime.date(1900, 1, 1), verbose_name='Data Inicio')),
                ('dt_fim', models.DateField(default=datetime.date(1900, 1, 1), verbose_name='Data Fim')),
                ('atividade', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app_fac.atividade')),
            ],
            options={
                'verbose_name_plural': 'Atividades Vinculadas',
            },
        ),
        migrations.CreateModel(
            name='Coordenador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('celular', models.CharField(max_length=20)),
                ('rc', models.IntegerField(default=0)),
                ('imagem', stdimage.models.StdImageField(force_min_size=False, upload_to=app_fac.models.user_manager.get_file_path, variations={'thumbnail': {'crop': True, 'height': 480, 'width': 480}}, verbose_name='Imagem')),
                ('data_expiracao', models.DateField(default=datetime.date(1900, 1, 1), verbose_name='Data de Expiracao')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='coordenador_usuario', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Coordenador',
                'verbose_name_plural': 'Coordenadores',
            },
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('descricao', models.TextField(default=None, max_length=2000)),
                ('destaque', models.CharField(default=None, max_length=255)),
                ('mercado_trabalho', models.TextField(max_length=1000)),
                ('imagem', stdimage.models.StdImageField(force_min_size=False, upload_to=app_fac.models.user_manager.get_file_path, variations={'thumbnail': {'crop': True, 'height': 500, 'width': 1500}}, verbose_name='Imagem')),
                ('imagem2', stdimage.models.StdImageField(force_min_size=False, upload_to=app_fac.models.user_manager.get_file_path, variations={'thumbnail': {'crop': True, 'height': 480, 'width': 480}}, verbose_name='Imagem dois')),
                ('coordenador', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='app_fac.coordenador')),
            ],
            options={
                'verbose_name': 'Curso',
                'verbose_name_plural': 'Cursos',
            },
        ),
        migrations.CreateModel(
            name='Disciplina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, unique=True)),
                ('data', models.DateField()),
                ('status', models.CharField(choices=[('AB', 'Aberto'), ('FC', 'Fechado')], default='AB', max_length=2)),
                ('plano_ensino', models.TextField(max_length=5000)),
                ('carga_horaria', models.IntegerField()),
                ('competencias', models.TextField(max_length=1000)),
                ('habilidades', models.TextField(max_length=1000)),
                ('ementa', models.TextField(max_length=5000)),
                ('Conteudo_programatico', models.TextField(max_length=5000)),
                ('bibliografia_basica', models.TextField(max_length=1000)),
                ('bibliografia_complementar', models.TextField(max_length=1000)),
                ('percentual_pratico', models.DecimalField(decimal_places=2, max_digits=13)),
                ('percentual_teorico', models.DecimalField(decimal_places=2, max_digits=13)),
            ],
            options={
                'verbose_name': 'Disciplina',
                'verbose_name_plural': 'Disciplinas',
            },
        ),
        migrations.CreateModel(
            name='Turma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('turma', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=4)),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app_fac.curso')),
            ],
            options={
                'verbose_name': 'Turma',
                'verbose_name_plural': 'Turmas',
            },
        ),
        migrations.CreateModel(
            name='SolicitacaoMatricula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dt_solicitacao', models.DateField()),
                ('status', models.CharField(choices=[('SO', 'Solicitada'), ('RE', 'Rejeitada'), ('AP', 'Aprovada'), ('CA', 'Cancelada')], default='SO', max_length=4)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app_fac.aluno')),
                ('coordenador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app_fac.coordenador')),
                ('curso', models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='app_fac.curso')),
            ],
            options={
                'verbose_name_plural': 'Solicitação de Matricula',
            },
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='', verbose_name='foto')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagem', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'imagem',
                'verbose_name_plural': 'imagens',
                'ordering': ('pk',),
            },
        ),
        migrations.CreateModel(
            name='Mensagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assunto', models.TextField(max_length=255)),
                ('referencia', models.TextField(max_length=255)),
                ('conteudo', models.TextField(max_length=255)),
                ('status', models.CharField(choices=[('EN', 'Enviado'), ('LI', 'Lido'), ('RE', 'Respondido')], max_length=3)),
                ('dt_envio', models.DateField()),
                ('dt_resposta', models.DateField()),
                ('resposta', models.TextField(max_length=1000)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app_fac.aluno')),
                ('professor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app_fac.professor')),
            ],
            options={
                'verbose_name_plural': 'Mensagens',
            },
        ),
        migrations.CreateModel(
            name='Matricula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dt_inicio', models.DateField()),
                ('dt_fim', models.DateField()),
                ('status', models.CharField(choices=[('AV', 'Ativa'), ('CA', 'Cancelada'), ('TA', 'Trancada'), ('AE', 'Analise')], default='AE', max_length=4)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app_fac.aluno')),
                ('curso', models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='app_fac.curso')),
                ('solicitacao_matricula', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app_fac.solicitacaomatricula')),
                ('turma', models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='app_fac.turma')),
            ],
            options={
                'verbose_name': 'Matricula',
                'verbose_name_plural': 'Matriculas',
            },
        ),
        migrations.CreateModel(
            name='EntregaAtividade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('resposta', models.TextField(max_length=255)),
                ('dt_entrega', models.DateField()),
                ('status', models.CharField(choices=[('EN', 'Entregue'), ('CO', 'Corrigido')], default='EN', max_length=2)),
                ('nota', models.DecimalField(decimal_places=2, max_digits=5)),
                ('dt_avaliacao', models.DateField()),
                ('obs', models.TextField(max_length=255)),
                ('file', models.FileField(blank=True, null=True, upload_to='file')),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app_fac.aluno')),
                ('atividade_vinculada', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app_fac.atividadevinculada')),
                ('professor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app_fac.professor')),
            ],
            options={
                'verbose_name_plural': 'Entrega das Atividades',
            },
        ),
        migrations.CreateModel(
            name='DisciplinaOfertada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dt_inicio', models.DateField()),
                ('dt_fim', models.DateField()),
                ('ano', models.IntegerField()),
                ('semestre', models.IntegerField()),
                ('metodologia', models.TextField(max_length=255)),
                ('recursos', models.TextField(max_length=255)),
                ('criterio_avaliacao', models.TextField(max_length=1000)),
                ('plano_aula', models.TextField(max_length=1000)),
                ('coordenador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app_fac.coordenador')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app_fac.curso')),
                ('disciplina', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app_fac.disciplina')),
                ('professor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app_fac.professor')),
                ('turma', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app_fac.turma')),
            ],
            options={
                'verbose_name_plural': 'Disciplinas Ofertadas',
                'unique_together': {('curso', 'disciplina', 'turma', 'ano', 'semestre')},
            },
        ),
        migrations.AddField(
            model_name='atividadevinculada',
            name='disciplina_ofertada',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app_fac.disciplinaofertada'),
        ),
        migrations.AddField(
            model_name='atividadevinculada',
            name='professor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app_fac.professor'),
        ),
    ]
