# Generated by Django 3.2.14 on 2022-09-05 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_fac', '0002_auto_20220905_2050'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('members', models.ManyToManyField(related_name='groups', to='app_fac.Person')),
            ],
        ),
    ]
