# Generated by Django 3.2.14 on 2022-09-06 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_group_person'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='person',
            options={'verbose_name': 'Person'},
        ),
        migrations.RemoveField(
            model_name='curso',
            name='disciplina_ofertada',
        ),
        migrations.AddField(
            model_name='curso',
            name='disciplina_ofertada',
            field=models.ManyToManyField(related_name='groups', to='app.DisciplinaOfertada'),
        ),
    ]
