# Generated by Django 3.2.14 on 2022-09-07 21:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20220905_2121'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='curso',
            name='disciplina_ofertada',
        ),
        migrations.AddField(
            model_name='disciplinaofertada',
            name='curso',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='app.curso'),
            preserve_default=False,
        ),
    ]
