# Generated by Django 3.2.14 on 2022-09-07 23:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20220907_1822'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='disciplina',
            name='coordenador',
        ),
        migrations.RemoveField(
            model_name='disciplinaofertada',
            name='coordenador',
        ),
    ]
