# Generated by Django 3.2.14 on 2022-09-07 23:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_fac', '0006_auto_20220907_2024'),
    ]

    operations = [
        migrations.AddField(
            model_name='turma',
            name='curso',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='app_fac.curso'),
        ),
    ]
